const signals = {
    REB1: 'REB1',
    REB2: 'REB2',
    eRE: 'eRE',
    RAB1: 'RAB1',
    RAB2: 'RAB2',
    eRA: 'eRA',
    RBB1: 'RBB1',
    RBB2: 'RBB2',
    eRB: 'eRB',
    RCB1: 'RCB1',
    RCB2: 'RCB2',
    eRC: 'eRC',
    RIB1: 'RIB1',
    RIB2: 'RIB2',
    eRI: 'eRI',
    RXB1: 'RXB1',
    RXB2: 'RXB2',
    eRX: 'eRX',
    COB1: 'COB1',
    COB2: 'COB2',
    eCO: 'eCO',
    eRAM: 'eRAM',
    eM: 'eM',
    sM: 'sM',
    RPB1: 'RPB1',
    RPB2: 'RPB2',
    eRP: 'eRP',
    XS: 'XS',
    XP1: 'XP1',
    ADD: 'ADD',
    SUB: 'SUB',
    MUL: 'MUL',
    AND: 'AND',
    OR: 'OR',
    XOR: 'XOR',
    FIN: 'FIN',
    REGSIGCLOCK: 'REGSIGCLOCK',
}

module.exports = {
    MAXIMUM_ALLOWED_BUS_POWER_TIME: 5,
    ATU_BETWEEN_UPDATE: 1,
    Signals: signals,
}
